# Generated by Django 5.0.3 on 2024-04-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mouse_dpi_alter_mouse_num_botones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouse',
            old_name='num_botones',
            new_name='numbotones',
        ),
    ]
