# Generated by Django 5.0.3 on 2024-05-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_moto_cilindraje_alter_moto_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=50)),
                ('apellido', models.TextField(blank=True, max_length=5000)),
                ('cedula', models.IntegerField()),
                ('telefono', models.TextField(blank=True, max_length=5000)),
                ('correo', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Moto',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
