# Generated by Django 5.0.4 on 2024-05-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
