# Generated by Django 5.0.3 on 2024-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.TextField(blank=True, max_length=50)),
                ('cilindraje', models.IntegerField(blank=True, max_length=5000)),
                ('modelo', models.TextField(blank=True, max_length=5000)),
                ('color', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
