# Generated by Django 5.0.3 on 2024-04-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='cilindraje',
            field=models.FloatField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='moto',
            name='modelo',
            field=models.FloatField(blank=True, max_length=5000),
        ),
    ]
