# Generated by Django 5.0.3 on 2024-05-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_moto_cilindraje_alter_moto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='cilindraje',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moto',
            name='marca',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='moto',
            name='modelo',
            field=models.IntegerField(),
        ),
    ]
